INSERT INTO BD.ROOM (ID, NAME, FIRSTFLOORCAPACITY, SECONDFLOORCAPACITY) VALUES (1, 'Blue submarine', 27, 45);
INSERT INTO BD.ROOM (ID, NAME, FIRSTFLOORCAPACITY, SECONDFLOORCAPACITY) VALUES (2, 'Green mexican', 45, 23);
INSERT INTO BD.ROOM (ID, NAME, FIRSTFLOORCAPACITY, SECONDFLOORCAPACITY) VALUES (3, 'TutyFruty', 12, 12);
INSERT INTO BD.ROOM (ID, NAME, FIRSTFLOORCAPACITY, SECONDFLOORCAPACITY) VALUES (4, 'Relation in the distance', 1, 1);