-- Demo data for the in-memory H2 database (loaded on every start).
-- Accounts: admin / admin (role admin) and demo / demo.

INSERT INTO ROOM (NAME, FIRSTFLOORCAPACITY, SECONDFLOORCAPACITY) VALUES ('Blue submarine', 27, 45);
INSERT INTO ROOM (NAME, FIRSTFLOORCAPACITY, SECONDFLOORCAPACITY) VALUES ('Green mexican', 45, 23);
INSERT INTO ROOM (NAME, FIRSTFLOORCAPACITY, SECONDFLOORCAPACITY) VALUES ('TutyFruty', 12, 12);
INSERT INTO ROOM (NAME, FIRSTFLOORCAPACITY, SECONDFLOORCAPACITY) VALUES ('Relation in the distance', 1, 1);

INSERT INTO PARTICIPANT (FIRSTNAME, LASTNAME, LOGIN, PASSWORD, ROLE, BIRTHDAY)
VALUES ('admin', 'admin', 'admin', '$2a$10$94TNnaTRTeH9E/o1OjZUoORNCaUOcpIZsKKyYu3kM39.ByR9MnnRW', 'admin', DATE '1990-01-01');
INSERT INTO PARTICIPANT (FIRSTNAME, LASTNAME, LOGIN, PASSWORD, ROLE, BIRTHDAY)
VALUES ('Demo', 'User', 'demo', '$2a$10$t.G9UZF1MEWaPc69W09cAO8Yk4uDeRXlnsc826CqsUH6vxc3lLaEm', NULL, DATE '1999-07-01');

-- dates are relative to today so the demo always has upcoming conferences
INSERT INTO CONFERENCE (NAME, ID_ROOM, NAME_ROOM, CAPACITY_ROOM, AMOUNT_PARTICIPANT, DATEE, TIMEE)
VALUES ('literary evening', 1, 'Blue submarine', 72, 0, DATEADD(DAY, 7, CURRENT_DATE), TIME '11:00:00');
INSERT INTO CONFERENCE (NAME, ID_ROOM, NAME_ROOM, CAPACITY_ROOM, AMOUNT_PARTICIPANT, DATEE, TIMEE)
VALUES ('How did I can?', 2, 'Green mexican', 68, 0, DATEADD(DAY, 14, CURRENT_DATE), TIME '17:00:00');
INSERT INTO CONFERENCE (NAME, ID_ROOM, NAME_ROOM, CAPACITY_ROOM, AMOUNT_PARTICIPANT, DATEE, TIMEE)
VALUES ('About fruit', 3, 'TutyFruty', 24, 0, DATEADD(DAY, 21, CURRENT_DATE), TIME '17:00:00');
INSERT INTO CONFERENCE (NAME, ID_ROOM, NAME_ROOM, CAPACITY_ROOM, AMOUNT_PARTICIPANT, DATEE, TIMEE)
VALUES ('Why did I cry', 4, 'Relation in the distance', 2, 0, DATEADD(DAY, 30, CURRENT_DATE), TIME '23:00:00');
