-- Works on H2 and PostgreSQL. Safe to run on every start.

CREATE TABLE IF NOT EXISTS ROOM
(
    ID                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME                VARCHAR(150) NOT NULL,
    FIRSTFLOORCAPACITY  INT          NOT NULL,
    SECONDFLOORCAPACITY INT          NOT NULL
);

CREATE TABLE IF NOT EXISTS PARTICIPANT
(
    ID                        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRSTNAME                 VARCHAR(100) NOT NULL,
    LASTNAME                  VARCHAR(100) NOT NULL,
    LOGIN                     VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD                  VARCHAR(100) NOT NULL,
    ROLE                      VARCHAR(20),
    BIRTHDAY                  DATE         NOT NULL,
    -- comma separated conference ids, e.g. "1,4,"
    ID_CONFERENCE_PARTICIPANT VARCHAR(10000),
    RATING                    INT
);

CREATE TABLE IF NOT EXISTS CONFERENCE
(
    ID                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME               VARCHAR(150) NOT NULL,
    NAME_ROOM          VARCHAR(150),
    ID_ROOM            INT          NOT NULL REFERENCES ROOM (ID),
    -- comma separated participant ids, e.g. "2,3,"
    ID_PARTICIPANT     VARCHAR(10000),
    CAPACITY_ROOM      INT          NOT NULL,
    AMOUNT_PARTICIPANT INT          NOT NULL,
    DATEE              DATE         NOT NULL,
    TIMEE              TIME
);
